package main

// agentEvent is a single event in the simulated agent tool-call loop.
// In a real agent these would be generated by parsing tool calls from an LLM
// response; here they are canned so the demo runs without an API key.
type agentEvent struct {
	eventType   string
	description string
	fields      map[string]any
}

// safeEvents returns the sequence of agent events for the safe prompt.
//
// The agent queries tickets by region and posts the aggregate report to an
// approved internal endpoint.  No PII is accessed; all verdicts should be
// allow or audit.
func safeEvents() []agentEvent {
	return []agentEvent{
		{
			eventType:   "tool_call",
			description: "query_tickets(region=EMEA, quarter=Q4-2025)",
			fields: map[string]any{
				"tool_name": "query_tickets",
				"arguments": "region=EMEA, quarter=Q4-2025",
			},
		},
		{
			eventType:   "tool_call",
			description: "query_tickets(region=APAC, quarter=Q4-2025)",
			fields: map[string]any{
				"tool_name": "query_tickets",
				"arguments": "region=APAC, quarter=Q4-2025",
			},
		},
		{
			eventType:   "external_request",
			description: "POST reports.internal.corp/q4-summary",
			fields: map[string]any{
				"domain": "reports.internal.corp",
				"method": "POST",
				"path":   "/q4-summary",
			},
		},
	}
}

// unsafeEvents returns the sequence of agent events for the unsafe prompt.
//
// The agent first reads a PII-classified customer record, then attempts to
// send it to an unapproved external email address.
// Expected: data_access → audit, external_request → deny.
func unsafeEvents() []agentEvent {
	return []agentEvent{
		{
			eventType:   "data_access",
			description: "get_customer_profile(account_id=10042) — classification: PII",
			fields: map[string]any{
				"classification": "PII",
				"record_id":      "10042",
				"tool_name":      "get_customer_profile",
			},
		},
		{
			eventType:   "external_request",
			description: "POST analyst@external-firm.com (unapproved domain)",
			fields: map[string]any{
				"domain": "external-firm.com",
				"method": "POST",
				"path":   "/send",
			},
		},
	}
}
